### ISSUE TITLE
Inconsistent time conversion for process hash calculation between procfs and kernel signals

### ISSUE THREAD

**Issue by hsandhu2309** [aquasecurity/tracee#4868]
## Description

While testing and using proctree, I observed that the process hashes obtained from procfs and those from kernel signals differ for the same process.

This happens in two main scenarios:

* When proctree is initially populated from procfs (I'm running Tracee with `--proctree source=both`), and a signal for a new process (`sched_process_exec` or `sched_process_fork`) arrives, the `FeedFromFork` and `FeedFromExec` handlers read the `parent_start_time` and calculate the parent hash.
* When `ProcFSLoop` runs at runtime, it fails to recognize that some processes already exist in the tree because the hash calculated from `procfs` differs from the one calculated from the signal.

From my debugging, I identified two causes:

In the `procfs` functions (`getProcessByPID`, `dealWithProc`, `dealWithThread`), the start time isn't converted to epoch time before hashing. Currently, it uses `startTimeNs := traceetime.ClockTicksToNsSinceBootTime(statStartTime)` ([link](https://github.com/aquasecurity/tracee/blob/33b1b84af93b4d68edf82f31ba2cd3b99cf404e0/pkg/proctree/proctree_procfs.go#L111)), but I believe it should be `startTimeNs := traceetime.BootToEpochNS(traceetime.ClockTicksToNsSinceBootTime(statStartTime))` to match the behavior used during signal handling.

When converting `start_time` from boot to nanoseconds, the result from `procfs` ends in multiple zeros (e.g., `1524976120000000`), while the kernel signal provides a more precise value (e.g., `1524976129897580`) for the same process.

If Tracee consistently uses boot time (not epoch time) to calculate hashes, this issue would be avoided. The hash function already rounds the `start_time` (arg2) to the nearest `10^7`, so using boot time directly ensures consistency. The problem arises when we convert to epoch time: the rounding leads to mismatched hashes, for example:

Signal: `1524976129897580 + 1754327201505193969 = 1755852177635091549 → rounded → 1755852177630000000`
Procfs: `1524976120000000 + 1754327201505193969 = 1755852177625193969 → rounded → 1755852177620000000`

This rounding difference causes the hash mismatch.

## Output of `tracee version`:

main-31145606f

## Output of `uname -a`:

Linux hutesh-tracee-1.c.security-tools-cluster.internal 6.11.0-1017-gcp #17~24.04.1-Ubuntu SMP Thu Jun 26 00:43:22 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yanivagman** [comment]
Hi @hsandhu2309,
thanks for the detailed debug info!

Although I agree that using boot time could have been better, we need to make sure we support older kernels where bpf helper to get process boottime was not available (tracee checks if it is available or not in bpf code). So I believe that for now we should keep the conversion to epoch time.

Can you please check if https://github.com/aquasecurity/tracee/pull/4873 fixes the issue for you?
BTW, this seems to be related to https://github.com/aquasecurity/tracee/issues/4835. Since I saw your comment there as well - did you get to the above conclusions while debuggin this other issue? Can we consider them dup or are these 2 different problems?

**Comment by hsandhu2309** [comment]
Hi @yanivagman ,
Thanks for your response and for providing PR #4873 to address the issue. For the first part of the issue (mismatch due to procfs not converting start time to epoch time), I had already implemented the same fix locally by using traceetime.BootToEpochNS in the procfs functions (getProcessByPID, dealWithProc, dealWithThread), and it works as expected. The changes in #4873 align with this and resolve the first part of the issue.

However, the second part of the issue—hash mismatches due to precision differences between procfs (e.g., 1524976120000000) and kernel signals (e.g., 1524976129897580)—remains unresolved by #4873. To fix this, I modified the HashTaskID function in hash.go. In my solution, I convert the received epoch time to boot time, round it to the nearest 10^7 to ensure consistency with both procfs and kernel signal times, and then convert it back to epoch time for hash creation. This approach eliminates the mismatch caused by differing time precisions.
Here’s the diff for my proposed change:

```diff
 func HashTaskID(arg1 uint32, arg2 uint64) uint32 {
-       round := arg2 / 10000000 // (1000000000 / USER_HZ) = 10000000
+       boot_time := traceetime.EpochToBootTimeNS(arg2)
+       round := boot_time / 10000000 // (1000000000 / USER_HZ) = 10000000
        round *= 10000000
-       return HashU32AndU64(arg1, round)
+       epoch_time := traceetime.BootToEpochNS(round)
+       return HashU32AndU64(arg1, epoch_time)
 }
```
This change ensures that both procfs and kernel signal times are aligned after rounding, resulting in consistent hashes. I’ve tested this locally, and it fully resolves the hash mismatch issue.
This change ensures that the `HashTaskID` function uses epoch time consistently, avoiding the mismatch caused by rounding differences. I’ve tested this locally, and it resolves the hash mismatch issue for both `procfs` and kernel signal scenarios.

Regarding #4835, we encountered this issue while debugging a problem where we were getting duplicate entries with different hashes in the proctree for the same process when retrieving lineage from proctree. The duplicates were caused by hash mismatches between processes received from procfs and kernel signals. After identifying the root cause as the time conversion and precision differences, we decided to post this as a separate issue.

Please let me know if you’d like me to provide further details!

Best regards,  
@hsandhu2309

**Comment by yanivagman** [comment]
Oh, I can see now.
The idea behind the round we had in  **HashTaskID** function is to avoid this exact problem of percision difference between procfs and kernel.
The problem with changing HashTaskID function is that it can be used in "analyze" mode (where events are sent from file in offline mode) and then the usage of **EpochToBootTimeNS** and **BootToEpochNS** functions will be incorrect (since there is no access to tracee process start time of when the events were captures in analyze mode).
So maybe another solution can be to remove one more digit when we round in the hash function:
```
 func HashTaskID(arg1 uint32, arg2 uint64) uint32 {
      round := arg2 / 100000000
      round *= 100000000
      return HashU32AndU64(arg1, round)
 }
```

Note the extra 0 in the first and second line of this function.
Can you please check if such a change works for you?

**Comment by LucaRocco** [comment]
Hi @yanivagman,

We actually tried this approach before, though I can’t quite recall why we didn’t stick with it. It might have been prior to realizing that the timestamps from`procfs` weren’t being converted to epoch time.

We’ll revisit this solution and let you know how it goes as soon as possible.

Thanks, Luca.

**Comment by yanivagman** [comment]
@LucaRocco I updated the PR with the percision change.
Please check if this resolves the issue you reported. Thanks.

**Comment by LucaRocco** [comment]
Hi @yanivagman,

It works, but just to clarify: this fix doesn’t completely solve the problem. As long as the operation order stays the same (convert boot time to epoch by simple addition, then round), the issue will persist. The root cause is the sum of the process `start_time` (since boot) and the system `boot_time`, which can cause an overflow. By rounding one more digit, we’re just reducing how often the problem happens. Please keep in mind these two points:

The sum of process `start_time` and `boot_time` can overflow beyond one digit. For example,
`1754327201608193969 + 1524976129997980 != 1754327201608193969 + 1524976120000000`
or
`1754327201698793969 + 1524976129696000 != 1754327201698793969 + 1524976120000000`.
The only real way to avoid this is to round the process `start_time` from signals to the nearest `10^7` before adding it to `boot_time`. This ensures the resulting value exactly matches the process `start_time` from `procfs`, converted from `ticks` to `boot_time`.

Increasing the rounding can cause collisions. With `10^8`, there’s a 100ms window where two processes could have the same PID. It’s unlikely given Linux’s PID reuse strategy, but we can’t guarantee it’s impossible.

Actually, I believe that since the 8th digit represents a value 10 times greater than the 7th, this fix might not even reduce the likelihood of the issue in all cases. For certain unlucky `boot_time` values with specific combinations in the last seven digits (for example, `8978699`, which contains many high digits), the problem could occur more frequently than with `boot_time` values that have lower digits at the end. This is just a consideration based on observation, I haven’t done a detailed analysis to confirm it.

Sorry for explaining the issue across multiple comments but we’re debugging and figuring it out as we go, so we update the issue whenever we learn something new.

Luca

**Comment by yanivagman** [comment]
> Hi [@yanivagman](https://github.com/yanivagman),
>

Hi @LucaRocco, and thanks for the feedback and detailed reply 

> It works, but just to clarify: this fix doesn’t completely solve the problem. As long as the operation order stays the same (convert boot time to epoch by simple addition, then round), the issue will persist. The root cause is the sum of the process `start_time` (since boot) and the system `boot_time`, which can cause an overflow. By rounding one more digit, we’re just reducing how often the problem happens. Please keep in mind these two points:
> 
> The sum of process `start_time` and `boot_time` can overflow beyond one digit. For example, `1754327201608193969 + 1524976129997980 != 1754327201608193969 + 1524976120000000` or `1754327201698793969 + 1524976129696000 != 1754327201698793969 + 1524976120000000`. The only real way to avoid this is to round the process `start_time` from signals to the nearest `10^7` before adding it to `boot_time`. This ensures the resulting value exactly matches the process `start_time` from `procfs`, converted from `ticks` to `boot_time`.
> 

Wer'e taking the hash AFTER we sum `start_time` with `boot_time` so we should be fine since adding two numbers can overflow at most one digit position.
The examples you provided actually demonstrate my point about single-digit carries. When you calculate:
1754327201608193969 + 1524976129997980 = 1754327203133170949
1754327201608193969 + 1524976120000000 = 1754327203128193969
The difference is ~5 million nanoseconds, not a multi-digit overflow in the addition operation. Addition carries only propagate one digit at a time mathematically.

> Increasing the rounding can cause collisions. With `10^8`, there’s a 100ms window where two processes could have the same PID. It’s unlikely given Linux’s PID reuse strategy, but we can’t guarantee it’s impossible.
> 

Valid point about the 100ms window. However, given Linux's PID cycling behavior and typical process lifetimes, the collision probability remains extremely low in practice.

> Actually, I believe that since the 8th digit represents a value 10 times greater than the 7th, this fix might not even reduce the likelihood of the issue in all cases. For certain unlucky `boot_time` values with specific combinations in the last seven digits (for example, `8978699`, which contains many high digits), the problem could occur more frequently than with `boot_time` values that have lower digits at the end. This is just a consideration based on observation, I haven’t done a detailed analysis to confirm it.

The boot_time digits don't fundamentally change the magnitude of the precision difference - they just determine where in the final number that difference appears. Since our rounding granularity (10^8) is much larger than the precision difference, it doesn't matter where in the number that difference manifests.

The fix works, as you mentioned and addresses the core issue effectively. The alternative approach of rounding signals before conversion would be significantly more complex and impact multiple code paths.

**Comment by LucaRocco** [comment]
Hi @yanivagman,

you are completely right, I got lost in simple math 😓. So the fix works perfectly and, as we agreed, the 100ms windows isn't a risk.

Thank you so much for your time.

Luca

**Comment by yanivagman** [comment]
No worries at all, Luca! 😄
Thanks for the thorough review and for working through the math with me. Even when we end up confirming the original approach, the discussion helps ensure we fully understand the solution.
I appreciate you taking the time to review this carefully!
